// <auto-generated />
namespace FCore.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class drop_req_ci_cbId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_req_ci_cbId));
        
        string IMigrationMetadata.Id
        {
            get { return "201705151559052_drop_req_ci_cbId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
