// <auto-generated />
namespace FCore.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class drop_req : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_req));
        
        string IMigrationMetadata.Id
        {
            get { return "201705150848276_drop_req"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
