// <auto-generated />
namespace FCore.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class perm_admin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(perm_admin));
        
        string IMigrationMetadata.Id
        {
            get { return "201704301959046_perm_admin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
