// <auto-generated />
namespace FCore.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ci_memberId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ci_memberId));
        
        string IMigrationMetadata.Id
        {
            get { return "201704291647213_ci_memberId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
