// <auto-generated />
namespace FCore.Identity.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class unhash_pass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unhash_pass));
        
        string IMigrationMetadata.Id
        {
            get { return "201706030934166_unhash_pass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
